#
# Playbook to deploy WEB
#
# Variables:
#
# operation: start|stop|restart
#
#
# Then run the playbook, like this:
#
# ansible-playbook -i inventory --limit=webhosts dpp_web_operate.yml --extra-vars "operation=restart"
#
- hosts: all
  gather_facts: true
  vars_files:
    - "roles/dpp_web_operate/defaults/{{ ansible_os_family | lower }}.yml"
  roles:
    - dpp_web_operate