#
# Playbook to deploy MS-PC
#
# Variables:
#
# operation: start|stop|restart
#
#
# Then run the playbook, like this:
#
# ansible-playbook -i inventory --limit=ms_pc_hosts ms-pc_operate.yml --extra-vars "operation=restart"
#
- hosts: all
  gather_facts: true
  vars_files:
    - "roles/ms-pc_operate/defaults/{{ ansible_os_family | lower }}.yml"
  roles:
    - ms-pc_operate