---

docker_edition: "ce"
docker_channel: "edge"

docker_version: "18.03.1"
docker_install_docker_compose: True
docker_compose_version: "1.21.2"

docker_users: []

docker_cron_tasks: []
  #- job: docker system prune -f
  #  name: "Docker clean up"
  #  schedule: ["0", "0", "*", "*", "0"]

docker_daemon_options: []

docker_apt_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | default('Ubuntu') | lower }} {{ ansible_distribution_release | default('xenial') }} {{ docker_channel }}"

docker_apt_cache_time: 86400

docker_pip_dependencies:
  - name: docker
  - name: docker-compose
  - name: ansible-tower-cli
