- name: Test CDVSID module
  uri:
    url: http://{{ ansible_fqdn }}:9001
    method: POST
    body: "{{ lookup('template','roles/cdvsid_operate/templates/XML_GetAllGroups.xml.j2') }}"
    status_code: 200
    headers:
      Content-Type: "application/xml"
    body_format: raw
    return_content: yes
  register: test_cdvsid
  delegate_to: localhost
  failed_when: "'error' in test_cdvsid.content"
  ignore_errors: true