  - name: "Start CDV"
    debug: msg="Starting CDV"

  - name: "Get Current Session Id"
    win_shell: |
      $server = "localhost"
      $users = @()
      # Query using quser, 2>$null to hide "No users exists...", then skip to the next server
      $quser = quser /server:$server 2>$null
      if(!($quser)){
          Continue
      }
      #Remove column headers
      $quser = $quser[1..$($quser.Count)]
      foreach($user in $quser){
        $usersObj = [PSCustomObject]@{SessionId=$Null}
        $quserData = $user -split "\s+"
        #We have to splice the array if the session is disconnected (as the SESSIONNAME column quserData[2] is empty)
        if(($user | select-string "{{ psexec_service_user.split('@')[0] }}") -eq $null){
            Continue
        }
        #We have to splice the array if the session is disconnected (as the SESSIONNAME column quserData[2] is empty)
        if(($user | select-string "Disc") -ne $null){
            #User is disconnected
            $quserData = ($quserData[0..1],"null",$quserData[2..($quserData.Length -1)]) -split "\s+"
        }
        # SessionID
        $users = $quserData[3]
      }
      return $users
    register: current_session_id

  - name: "Start CDV service"
    win_command: "{{ tools_path }}{{ path_separator }}PSTools{{ path_separator }}PSExec64.exe -accepteula -nobanner -h -s -w {{ project_root }}\\current\\ -i {{ current_session_id.stdout | int }} cmd /c start {{ project_root }}\\current\\CDVSID.exe"

  - name: "Wait to ensure service is working"
    win_wait_for:
      port: "{{ service_port }}"
      delay: 10
      retries: 60
      state: started

  - name: "Copy Activate SQL file"
    local_action:
      module: template
      src: "roles/cdvsid_operate/templates/sql/activate_service.sql.j2"
      dest: "/tmp/activate_cdv.sql"

  - name: "Activate CDV"
    local_action:
      module: mssql_db
      name: 'BDSIGGER'
      login_host: '{{ cdv_db_host }}'
      login_user: '{{ cdv_db_user }}'
      login_password: '{{ cdv_db_password }}'
      login_port: '{{ cdv_db_port }}'
      state: import
      target: '/tmp/activate_cdv.sql'

  - name: "Remove Activate SQL file"
    local_action:
      module: file
      state: absent
      path: "/tmp/activate_cdv.sql"

  - name: "Wait to ensure no task processing"
    pause:
      seconds: 10