---
# This Playbook runs the specific plays in broker2

- replace:
    dest: "{{ kafka_app_dir }}/config/server.properties"
    regexp: 'broker.id=0'
    replace: 'broker.id=2'
    backup: yes

- lineinfile:
    dest: "{{ zookeeper_app_dir }}/conf/zoo.cfg"
    line: "server.1=broker1:2888:3888"
    insertafter: EOF

- lineinfile:
    dest: "{{ zookeeper_app_dir }}/conf/zoo.cfg"
    line: "server.2=0.0.0.0:2888:3888"
    insertafter: EOF

- lineinfile:
    dest: "{{ zookeeper_app_dir }}/conf/zoo.cfg"
    line: "server.3=broker3:2888:3888"
    insertafter: EOF

- name: Create the {{ zookeeper_data_dir }}/myid file
  copy:
    dest: "{{ zookeeper_data_dir }}/myid"
    content: |
      2