---

###
service_name: "CDV"
psexec_service_user: "svc_ansible_admin"

#### ARTIFACT Info

nexus_url: "http://desreposrv.rentalcar.es:10081"

nexus_repository: "{{ nexus_url }}/repository/SAR/"
nexus_artifact_name: "CDVSID.exe"
nexus_artifact_version: "{{ cdvsid_version | default('1.06.000-683a7a0') }}"
nexus_artifact_file: "{{ nexus_artifact_name }}-{{ nexus_artifact_version }}.7z"
nexus_artifact_path: "{{ nexus_repository }}{{ nexus_artifact_file }}"

####

project_root: "{{ project_installation_dest }}"
project_release: "{{ cdvsid_version }}"
project_artifact_name: "{{ nexus_artifact_name }}-{{ project_release }}"
project_extract_artifact_name: "{{ nexus_artifact_name }}-{{ project_release }}"
project_final_filename: "{{ nexus_artifact_file }}"
project_deploy_strategy: "nexus"
project_keep_releases: "2"
project_unwanted_items: [ '.git' ]

####

cdv_db_host: "{{ ansible_hostname }}"
cdv_db_port: "1433"
cdv_db_user: "sa"
cdv_db_password: "testing2018"