---
- name: "(Install GeoIP Module: All OSs) Install NGINX Open Source GeoIP Module"
  package:
    name: nginx-geoip-perl
    state: present
  when: type == "opensource"

- name: "(Install GeoIP Module: All OSs) Install NGINX Plus GeoIP Module"
  package:
    name: nginx-plus-geoip-perl
    state: present
  when: type == "plus"

- name: "(Setup GeoIP Module: All NGINX) Load NGINX GeoIP Module"
  blockinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    block: |
      load_module modules/ngx_http_geoip_module.so;
      load_module modules/ngx_stream_geoip_module.so;
  notify: "Reload NGINX"
