---
- name: "(Install Image Filter Module: All OSs) Install NGINX Open Source Image Filter Module"
  package:
    name: nginx-module-image-filter
    state: present
  when: type == "opensource"
  become: true

- name: "(Install Image Filter Module: All OSs) Install NGINX Plus Image Filter Module"
  package:
    name: nginx-plus-module-image-filter
    state: present
  when: type == "plus"
  become: true

- name: "(Setup Image Filter Module: All NGINX) Load NGINX Image Filter Module"
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: load_module modules/ngx_http_image_filter_module.so;
  notify: "Reload NGINX"
  become: true
