---
- name: "(Install RTMP Module: All OSs) Install NGINX Open Source RTMP Module"
  package:
    name: nginx-module-rtmp
    state: present
  when: type == "opensource"

- name: "(Install RTMP Module: All OSs) Install NGINX Plus RTMP Module"
  package:
    name: nginx-plus-module-rtmp
    state: present
  when: type == "plus"

- name: "(Setup RTMP Module: All NGINX) Load NGINX RTMP Module"
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: load_module modules/ngx_rtmp_module.so;
  notify: "Reload NGINX"
