  - name: "Stop PRI"
    debug: msg="Stopping PRI"

  - name: "Get Current Session Id"
    win_shell: |
      $server = "localhost"
      $users = @()
      # Query using quser, 2>$null to hide "No users exists...", then skip to the next server
      $quser = quser /server:$server 2>$null
      if(!($quser)){
          Continue
      }
      #Remove column headers
      $quser = $quser[1..$($quser.Count)]
      foreach($user in $quser){
        $usersObj = [PSCustomObject]@{SessionId=$Null}
        $quserData = $user -split "\s+"
        #We have to splice the array if the session is disconnected (as the SESSIONNAME column quserData[2] is empty)
        if(($user | select-string "{{ psexec_service_user.split('@')[0] }}") -eq $null){
            Continue
        }
        #We have to splice the array if the session is disconnected (as the SESSIONNAME column quserData[2] is empty)
        if(($user | select-string "Disc") -ne $null){
            #User is disconnected
            $quserData = ($quserData[0..1],"null",$quserData[2..($quserData.Length -1)]) -split "\s+"
        }
        # SessionID
        $users = $quserData[3]
      }
      return $users
    register: current_session_id

  - name: "Copy Deactivate SQL file"
    local_action:
      module: template
      src: "roles/dpp_pri_operate/templates/sql/deactivate_service.sql.j2"
      dest: "/tmp/deactivate_pri.sql"

  - name: "Deactivate PRI"
    local_action:
      module: mssql_db
      name: 'BDSIGGER'
      login_host: '{{ pri_db_host }}'
      login_user: '{{ pri_db_user }}'
      login_password: '{{ pri_db_password }}'
      login_port: '{{ pri_db_port }}'
      state: import
      target: '/tmp/deactivate_pri.sql'
    register: deactivate_pri_db

  - name: "Remove Deactivate SQL file"
    local_action:
      module: file
      state: absent
      path: "/tmp/deactivate_pri.sql"

  - name: "Wait to ensure no task processing"
    pause:
      seconds: 30

  - name: "( STOP - PRI ) - Stop PRI instance"
    win_command: "{{ tools_path }}{{ path_separator }}PSTools{{ path_separator }}PSExec64.exe -accepteula -nobanner -h -s -i {{ current_session_id.stdout | int }} cmd /c start {{ project_root }}{{ path_separator }}current{{ path_separator }}pri{{ path_separator }}check_pri.bat"
    register: pri_stopped_bat