- name: Check to see if there is a current version
  win_stat: path="{{ project_root }}/current"
  register: current_version_installed

- name: "Stop {{ service_name }}"
  include_tasks: stop.yml
  when: (operation | default(False) == "stop" or operation | default(False) == "restart") and current_version_installed.stat.exists

- name: "Start {{ service_name }}"
  include_tasks: start.yml
  when: (operation | default(False) == "start" or operation | default(False) == "restart") and current_version_installed.stat.exists

- name: "Get Current {{ service_name }} Version"
  include_tasks: get_version.yml
  when: (operation | default(False) == "get_version") and current_version_installed.stat.exists